backend:
  name: github
  repo: UniPlanTeam/uniplanteam.github.io

media_folder: "assets/images/uploads"

collections:
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Categories"
        name: "categories"
        widget: "list"
      - label: "Body"
        name: "body"
        widget: "markdown"
